feat(deploy): add deploy status check

diff --git a/deployment/acr-trigger/pipeline.yaml b/deployment/acr-trigger/pipeline.yaml
--- a/deployment/acr-trigger/pipeline.yaml
+++ b/deployment/acr-trigger/pipeline.yaml
@@ -26,25 +26,49 @@ spec:
       command:
       - sh
       args:
-        - -c
-        - |
-          echo "pre-deploy success!!"
+      - -c
+      - |
+        echo "pre-deploy: success!!"
+      volumeMounts:
+      - name: result
+        mountPath: /app/result/
     - name: deploy
       image: registry.cn-hangzhou.aliyuncs.com/knative-sample/deployer:master_0f27a4dc-20191213170052
       command:
-      - /deployer
+      - sh
       args:
-      - --image=$(inputs.params.imageUrl):$(inputs.params.imageTag)
-      - --ksvcname=$(inputs.params.ksvcname)
-      - --namespace=$(inputs.params.namespace)
+      - -c
+      - |
+        /deployer --image=$(inputs.params.imageUrl):$(inputs.params.imageTag) --ksvcname=$(inputs.params.ksvcname) --namespace=$(inputs.params.namespace)
+        if [ $? -eq 0 ]; then
+            echo "SUCCESS" > /app/result/deploy
+        else
+            echo "FAILED" > /app/result/deploy
+        fi
+      volumeMounts:
+      - name: result
+        mountPath: /app/result/
     - name: post-deploy
       image: registry.cn-hangzhou.aliyuncs.com/knative-sample/alpine:3.10.3
       command:
       - sh
       args:
-        - -c
-        - |
-          echo "post-deploy success!!"
+      - -c
+      - |
+        if grep -Fxq "SUCCESS" /app/result/deploy 2>/dev/null
+        then
+            echo "post-deploy: --image=$(inputs.params.imageUrl):$(inputs.params.imageTag) --ksvcname=$(inputs.params.ksvcname) --namespace=$(inputs.params.namespace) deploy SUCCESS!!"
+        else
+            echo "post-deploy: --image=$(inputs.params.imageUrl):$(inputs.params.imageTag) --ksvcname=$(inputs.params.ksvcname) --namespace=$(inputs.params.namespace) deploy FAILED!!"
+        fi
+      volumeMounts:
+      - name: result
+        mountPath: /app/result/
+
+  volumes:
+  - name: result
+    emptyDir: {}
+
 --- 
 apiVersion: tekton.dev/v1alpha1
 kind: Pipeline
